import json
import os
from flask import Flask, request, jsonify, render_template
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

ai_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

app = Flask(__name__)
current_itinerary = []
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev-secret-key")


@app.route("/", methods=["GET"])
def index():
    return render_template("index.html")


@app.route("/plan", methods=["POST"])
def plan():
    data = request.get_json()
    budget = float(data.get("budget", 0))
    days = int(data.get("days", 1))
    destination = data.get("destination", "your destination")

    global current_itinerary
    current_itinerary = []

    prompt = f"""
You are an expert travel planner. Create a detailed itinerary for {days} days in {destination} with a total budget of {budget} USD.
Return the response as a JSON array with exactly {days} objects, each having:
- "day": (number starting from 1)
- "activity": (description of activity for that day, keep it concise under 80 characters)
- "cost": (estimated cost for that day in USD, as a number)
Do not include any extra text, only the JSON array.
"""

    try:
        response = ai_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": "You are a JSON generator. Output only valid JSON.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
        )
        raw = response.choices[0].message.content
        # Remove markdown code fences if present
        if raw.startswith("```json"):
            raw = raw[7:]
        if raw.endswith("```"):
            raw = raw[:-3]
        parsed = json.loads(raw)
        itinerary_data = (
            parsed if isinstance(parsed, list) else next(iter(parsed.values()))
        )
        for item in itinerary_data:
            current_itinerary.append(
                {"day": item["day"], "activity": item["activity"], "cost": item["cost"]}
            )
    except Exception as e:
        print(f"Groq failed: {e}. Using fallback plan.")
        for day in range(1, days + 1):
            daily = budget / days
            if daily > 150:
                activity = "🏨 Luxury hotel + 🍽️ Fine dining"
                cost = 120
            elif daily > 60:
                activity = "🏡 Mid-range hotel + 🍜 Local food"
                cost = 70
            else:
                activity = "🛌 Hostel + 🥪 Street food"
                cost = 30
            current_itinerary.append({"day": day, "activity": activity, "cost": cost})

    # ========== تحسين شكل الجدول (تصميم بطاقات حديث) ==========
    cards_html = ""
    for item in current_itinerary:
        cards_html += f"""
        <div class="card mb-3 shadow-sm border-start border-4 border-primary">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-md-2 text-center text-md-start mb-2 mb-md-0">
                        <span class="badge bg-primary rounded-pill px-3 py-2 fs-6">Day {item["day"]}</span>
                    </div>
                    <div class="col-md-7 mb-2 mb-md-0">
                        <i class="bi bi-pin-angle-fill text-primary me-2"></i>
                        <strong>{item["activity"]}</strong>
                    </div>
                    <div class="col-md-3 text-md-end">
                        <span class="text-success fw-bold fs-5">${item["cost"]}</span>
                    </div>
                </div>
            </div>
        </div>
        """

    html_table = f"""
    <div class="card shadow-lg border-0 mt-4">
        <div class="card-header bg-gradient-primary text-white py-3" style="background: linear-gradient(135deg, #1e2a5e, #2b3b6e);">
            <h4 class="mb-0"><i class="bi bi-journal-bookmark-fill me-2"></i>Your AI-Powered Itinerary</h4>
            <p class="mb-0 small opacity-75">📍 {destination} | 💰 ${budget} | 📅 {days} days</p>
        </div>
        <div class="card-body p-4">
            {cards_html}
        </div>
        <div class="card-footer bg-light text-muted small text-end">
            <i class="bi bi-robot"></i> Generated by Groq AI · Edit any day using the buttons below
        </div>
    </div>
    """
    return jsonify({"status": "success", "html_table": html_table})


@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({"status": "healthy"})


@app.route("/update_day", methods=["POST"])
def update_day():
    global current_itinerary
    data = request.get_json()
    day_index = int(data.get("day_index"))
    new_activity = data.get("new_activity")
    new_cost = float(data.get("new_cost"))

    if day_index < 0 or day_index >= len(current_itinerary):
        return jsonify({"status": "error", "message": "Invalid day index"}), 400

    current_itinerary[day_index]["activity"] = new_activity
    current_itinerary[day_index]["cost"] = new_cost

    # إعادة بناء البطاقات بنفس الشكل الجديد
    cards_html = ""
    for item in current_itinerary:
        cards_html += f"""
        <div class="card mb-3 shadow-sm border-start border-4 border-primary">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-md-2 text-center text-md-start mb-2 mb-md-0">
                        <span class="badge bg-primary rounded-pill px-3 py-2 fs-6">Day {item["day"]}</span>
                    </div>
                    <div class="col-md-7 mb-2 mb-md-0">
                        <i class="bi bi-pin-angle-fill text-primary me-2"></i>
                        <strong>{item["activity"]}</strong>
                    </div>
                    <div class="col-md-3 text-md-end">
                        <span class="text-success fw-bold fs-5">${item["cost"]}</span>
                    </div>
                </div>
            </div>
        </div>
        """

    html_table = f"""
    <div class="card shadow-lg border-0 mt-4">
        <div class="card-header bg-gradient-primary text-white py-3" style="background: linear-gradient(135deg, #1e2a5e, #2b3b6e);">
            <h4 class="mb-0"><i class="bi bi-pencil-square me-2"></i>Updated Itinerary</h4>
            <p class="mb-0 small opacity-75">✏️ Manually edited</p>
        </div>
        <div class="card-body p-4">
            {cards_html}
        </div>
        <div class="card-footer bg-light text-muted small text-end">
            <i class="bi bi-robot"></i> Changes saved
        </div>
    </div>
    """
    return jsonify({"status": "success", "html_table": html_table})


if __name__ == "__main__":
    port = int(os.getenv("PORT", 8000))
    app.run(host="0.0.0.0", port=port, debug=True)
